### ISSUE TITLE
[BUG] -  Error al ejecutar test Selenium

### ISSUE THREAD

**Issue by danielhingar** [AlfonsoRodriguezRomero/decide#26]
#Description of the issue
* He creado un test con Selenium, lo he exportado como archivo python, lo he añadido al proyecto decide y he ejecutado el comando 'python3 ./manage.py test voting' para ejecutar los test del módulo voting en el que está incluido el susodicho.

Adjunto la traza:
Traceback (most recent call last):
  File "/home/usuario/.local/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/usuario/decide/decide/voting/test_selenium.py", line 22, in test_createvoting
    self.driver.get("http://localhost:8000/voting/")
AttributeError: 'TestCreatevoting' object has no attribute 'driver'

#Configuration parameters
* El IDE que estoy empleando es Visual Studio, estoy utilizando la versión del proyecto que está en la rama daniel-develop y he instalado selenium en su versión 2.33.0.

#Proposed solution
Supongo que error puede estar al instalar los driver de firefox para reproducir el código.

**Comment by danielhingar** [comment]
El problema estaba en una url donde instalábamos geckodriver, en vez de usar /usr/bin/geckodriver tenemos que usar usr/local/bin/geckodriver ya que es la carpeta local la que usa nuestro proyecto
