### ISSUE TITLE
[BUG] -  Error test Selenium

### ISSUE THREAD

**Issue by danielhingar** [AlfonsoRodriguezRomero/decide#30]
Este bug se ha producido al ejecutar un test del módulo voting realizado con selenium, a través de la terminal de forma local usando el comando 'python3 ./manage.py test voting' .
La traza del terminal donde se produjo el error es la siguiente:

Traceback (most recent call last):
  File "/home/usuario/.local/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/usuario/decide/decide/voting/test_selenium.py", line 59, in test_delete
    self.driver.find_element(By.ID,"id_password").send_keys("decide1234")
NameError: name 'By' is not defined

Como parámetros de configuración tengo Visual Studio, estoy utilizando una máquina virtual de ubuntu, tengo instalado geckodriver en su versión 0.24.0 para linux y he utilizado el IDE de selenium para firefox para crear el test.

Como propuesta sugiero usar stackoverflow.

**Comment by danielhingar** [comment]
Para solucionar este error hay que cambiar la nomenclatura, en vez de usar  "self.driver.find_element(By.ID,"id_password").send_keys("decide1234")" tenemos que sustituirlo por "self.driver.find_element_by_id("id_password").send_keys("decide1234"). 
Otra solución sería importar la librería By de selenium.webdriver.common.by.
